packages:
    - "back"
    - "front"
    - "packages/*"
allowBuilds:
    bcrypt: false
    better-sqlite3: true
    esbuild: false
    protobufjs: false
    sharp: false
    sqlite3: false
    unrs-resolver: false
